name: 'build'
on:
  pull_request:
  push:
    branches:
      - "*"
      - "!main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Test the code
        run: |
          pipx install poetry && \
          poetry install && \
          poetry run pytest && \
          poetry run ruff check
